export const diAuthorizationLetter = `
DEMAND INTERLOCK AUTHORIZATION — Q3 2026
IBM Consulting — Global Capacity Management

Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
Prepared by: Agentic CPI System
Authorization Level: GEO COO / CFO

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TO: Service Line Leads, GEO COOs, CFO Office
RE: Q3 2026 Demand Interlock — Capacity Authorization

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. EXECUTIVE SUMMARY

This authorization covers the Q3 2026 capacity plan spanning 32 centers, 36 practices, and 7 band levels across all 5 GEOs. Total validated demand: 18,916 HC. Current supply: 14,227 HC. Net gap requiring fulfillment action: 2,931 HC.

Eight (8) CritSit gaps have been identified requiring immediate executive attention, primarily in SAP Application Ops (Americas, EMEA, Japan), Quality Engineering (EMEA, APAC), and AI & Analytics (Americas, APAC).

2. AUTHORIZED ACTIONS

The following fulfillment actions are authorized under the Base scenario:

  a) BENCH REDEPLOYMENT: 586 HC across all GEOs
     - Priority: CritSit gaps in SAP and QE practices
     - Cross-geo redeployment authorized for CritSit only

  b) INTERNAL ROTATION: 293 HC
     - Java-to-Open Source pathway: 40 HC (Americas)
     - Infrastructure-to-Cloud pathway: 28 HC (EMEA)
     - Backend-to-Frontend pathway: 25 HC (UKI)

  c) RESKILL / ANOB: 440 HC
     - SAP Academy fast-track: 80 HC across EMEA + APAC
     - AI/ML certification program: 45 HC (Americas + APAC)
     - QE Automation bootcamp: 120 HC (FNC Global)
     - TRAM authorization letters to be generated upon approval

  d) EXTERNAL HIRE: 879 HC
     - Budget authorized: $28.0M
     - Priority bands: B6-B8 (92% of hires)
     - 60-day average lead time assumed

  e) SUB-K CONTRACTORS: 527 HC
     - Budget authorized: $22.0M
     - CritSit bridge coverage: 180 HC immediate
     - SAP Fieldglass POs to be raised within 48 hours of approval

  f) HCAM / FTH: 206 HC
     - Fixed-term positions for demand with <6 month visibility
     - HCAM approval routing: GEO COO → CFO

3. FINANCIAL IMPACT

  Total fulfillment investment: $50.0M
  Projected cGP impact: -$120M (Base scenario)
  Utilization delta: -1.4pp vs. target
  Revenue at risk (unfilled gaps): $176.4M

4. APPROVAL REQUIRED

  □ GEO COO — Americas
  □ GEO COO — EMEA
  □ GEO COO — APAC
  □ GEO COO — Japan
  □ GEO COO — UKI
  □ Global CFO
  □ BPOD Lead

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Agentic CPI v1.0 — Capacity Planning Intelligence
Auto-populated into SCORE upon final approval
`;

export const scorePlanSummary = `
SCORE PLAN SUMMARY — Q3 2026
━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SITUATION
IBM Consulting faces a 2,931 HC gap against validated Q3 demand of 18,916 across 5 GEOs. Eight CritSit gaps threaten $89.2M in revenue, concentrated in SAP Application Ops, Quality Engineering, and AI & Analytics practices.

COMPLICATION
Three structural challenges compound the gap:
1. SAP S/4HANA migration wave creating unprecedented demand for ABAP HANA specialists — 3x historical run rate
2. AI talent market tightening — Data Scientist-AI roles show 5.0 fill difficulty score (max)
3. Revenue forecasts exceed visible deal pipeline by 35% on average across critical JRS roles, suggesting either pipeline lag or over-commitment in financial planning

OPTIONS EVALUATED
Conservative: Fill 1,973 of 2,931 gaps. cGP impact: -$82M. Leaves $94M revenue at risk.
Base: Fill 2,931 gaps via full lever activation. cGP impact: -$120M. Addresses all identified gaps.
Flex: Proactive posture for 3,580 projected gaps. cGP impact: -$165M. Captures $45-65M upside.

RECOMMENDATION
Proceed with Base scenario with Flex triggers:
- Immediate: Activate Base fulfillment plan across all GEOs
- 30-day gate: Review signed pipeline vs. forecast — if win rate exceeds 80%, escalate to Flex
- CritSit: Authorize immediate SubK engagement for 8 critical gaps ($8.2M)
- Monthly TI cadence to validate demand trajectory

EVIDENCE
- Historical fill rate at Base assumptions: 84.5% (3-quarter trailing average)
- SubK cost premium justified by $176.4M revenue at risk
- FNC Global QE factory has 115% stretch capacity available
- Cross-geo redeployment saved $12M in Q1 2026 (Americas→APAC SAP transfer)

KEY METRICS FOR TRACKING
- Gap closure rate (target: 85% by Week 8)
- CritSit resolution (target: 100% bridge coverage by Week 2)
- SubK-to-FTE conversion (target: 40% within 6 months)
- Demand delta (bottoms-up vs top-down) trend — narrowing = healthy
`;
